name: test-mobilenet

on:
#    push:
#        branches:
#            - all-tuts-together
    pull_request:
        branches:
            - main
        paths:
            - 'notebooks/mobilenet-rps/*'

jobs:
    test: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build container
              run: |
                cd ./notebooks/mobilenet-rps
                docker build -t test-image .
            - name: Run test in container
              run: |
                docker run --rm test-image
